server:
  port: 8088

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  mapper-locations: classpath:/Mapper/*Mapper.xml

spring:
  profiles:
    active: dev